# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a89fa369596c1202081dbf63e506849720d0505e704be64feb8c2a63484ac3929b9823a8703b577935fa75571752ccf72c3933d503629b5f6080d34eb206dd0

test:
  secret_key_base: b2c7e7b6dc540716860996c0fd74f7ad23d98f6d171d9b099720cebcac428506e9407407c350d39db0ae16198661fc7a1994086e509111d74b8b1de0682c18f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
